create extension if not exists "pgcrypto";

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  cost numeric(12,2) default 0,
  description text,
  category text,
  material text,
  color_finish text,
  care_instructions text,
  warranty_text text default 'مقاوم للصدأ ولا يتغير لونه مع الماء',
  image_url text,
  gallery_images jsonb default '[]'::jsonb,
  video_url text,
  stock_qty integer default 0,
  discount_type text default 'percent' check (discount_type in ('percent', 'fixed')),
  discount_value numeric default 0,
  discount_active boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  title text not null,
  count text,
  image text,
  quote text,
  author text,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null unique,
  email text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number bigint generated by default as identity unique,
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  customer_location text,
  total_price numeric(12,2) not null default 0,
  subtotal numeric(12,2) not null default 0,
  status text not null default 'pending',
  order_source text default 'other',
  items jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text,
  discount_type text not null default 'percent' check (discount_type in ('percent', 'fixed')),
  discount_value numeric(12,2) not null default 0,
  min_order numeric(12,2) default 0,
  active boolean not null default true,
  used_count integer not null default 0,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  customer_name text not null default 'زبون',
  rating integer not null check (rating between 1 and 5),
  comment text not null,
  image_urls jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.general_inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  material text,
  quantity numeric not null default 0,
  price numeric(12,2) not null default 0,
  unit text,
  low_stock_threshold numeric default 0,
  low_stock_alerted boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_activity_log (
  id bigint generated by default as identity primary key,
  action text not null,
  details text,
  created_at timestamptz not null default now()
);

create table if not exists public.monthly_archives (
  id bigint generated by default as identity primary key,
  month_year text not null unique,
  total_sales numeric(12,2) not null default 0,
  orders_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.product_reviews enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.coupons enable row level security;
alter table public.general_inventory enable row level security;
alter table public.admin_users enable row level security;
alter table public.admin_activity_log enable row level security;
alter table public.monthly_archives enable row level security;

create policy "Public can view active products" on public.products for select using (is_active = true);
create policy "Public can view categories" on public.categories for select using (true);
create policy "Public can view reviews" on public.product_reviews for select using (true);
create policy "Public can add reviews" on public.product_reviews for insert with check (true);

create policy "Authenticated users can manage products" on public.products for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage categories" on public.categories for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage reviews" on public.product_reviews for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage customers" on public.customers for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage orders" on public.orders for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage coupons" on public.coupons for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage inventory" on public.general_inventory for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage admins" on public.admin_users for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage activity" on public.admin_activity_log for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage archives" on public.monthly_archives for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true), ('category-images', 'category-images', true)
on conflict (id) do update set public = excluded.public;

create policy "Public can view product images" on storage.objects for select using (bucket_id in ('product-images', 'category-images'));
create policy "Authenticated users can upload store images" on storage.objects for insert to authenticated with check (bucket_id in ('product-images', 'category-images'));
create policy "Authenticated users can update store images" on storage.objects for update to authenticated using (bucket_id in ('product-images', 'category-images'));
create policy "Authenticated users can delete store images" on storage.objects for delete to authenticated using (bucket_id in ('product-images', 'category-images'));
